### ISSUE TITLE
Suggestion: using Git LFS to store large files instead of releases

### ISSUE THREAD

**Issue by ryanfortner** [Pi-Apps-Coders/files#36]
Git LFS is a file-storage solution for large files in a GitHub repository: https://git-lfs.github.com

I just set it up in one of my own personal repo and it works great and is simple to use. I suggest we begin using it so we can keep all files in the master tree instead of in releases.

**Comment by theofficialgman** [comment]
I'll play around with it soon enough.
the reason releases were used was because they don't contribute to repo size bloat when adding or removing files from the repo. no commit needs to be made to add a release and no special git extension needs to be installed.

with a normal git repo, you have the size limitations as well as the fact that even removing a file from a git repo doesn't remove it from the history, meaning a full clone of the repo will get larger and larger over time

**Comment by theofficialgman** [comment]
also from what I am reading, the amount of free LFS is EXTREMELY small. we can't work with only 1GB of total storage
https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-storage-and-bandwidth-usage

**Comment by theofficialgman** [comment]
confirmed, only 1GB of storage is free and the monthly cost is very high

![image](https://user-images.githubusercontent.com/28281419/207969248-1c3c3982-fcb4-49a7-a25e-0258922db005.png)

**Comment by Botspot** [comment]
Using Releases may not be considered the most elegant solution by some, but our other free options are archive.org (very slow) or Google drive (limits total downloads).

**Comment by ryanfortner** [comment]
Oh ok. I was not aware of the strict limitations. Maybe consider trying OSDN, if you'd like an alternative to GitHub? https://osdn.net

It's got a ton of mirrors worldwide and no storage limits that I'm aware of. I used it for raspbian addons and never had any problems with it.
